/*
* Data access layer methods. Here are the methods needed to access the firebase database
*/

const admin = require('firebase-admin');
const functions = require('firebase-functions');

admin.initializeApp(functions.config().firebase);
const db = admin.firestore();
const collectionName = 'events';

exports.getAllEvents = () => {
    return db.collection(collectionName).get();
};

/*
* id: firebase database id (autogenerated on addEvent)
*/
exports.getEventById = id => {
    let eventRef = db.collection(collectionName).doc(id);
    return eventRef.get();
};

/*
* event: full event object to add in the database
*/
exports.addEvent = event => {
    return db.collection(collectionName).add(event);
};

// /*
// * id: firebase database id (autogenerated on addEvent)
// * event: full event object to update in the database
// */
exports.updateEventById = (id, event) => {
    let docRef = db.collection(collectionName).doc(id);
    return docRef.update(event);
};

// /*
// * id: firebase database id (autogenerated on addEvent)
// */
exports.deleteEventById = id => {
    return db.collection(collectionName).doc(id).delete();
};